version: "3.8"

services:
  mikrotik:
    build: .
    container_name: mikrotik_qemu
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "8291:8291" # Winbox
      - "2222:22" # SSH
      - "9865:80" # Webfig HTTP
      - "9443:443" # Webfig HTTPS
      - "500:500/udp" # L2TP/IPsec ISAKMP
      - "4500:4500/udp" # L2TP/IPsec NAT-T
      - "1701:1701/udp" # L2TP
      - "1723:1723" # PPTP
    stdin_open: true
    tty: true
