version: "3.8"

services:
  mikrotik:
    build: .
    container_name: mikrotik_qemu
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true
